"""The configure stage: what file goes where on each VM.

The files themselves are generated in pre-start, so the paths declared here do
not exist yet.
"""

from typing import Final

from phenix_apps.apps.sceptre import simulators
from phenix_apps.apps.sceptre.hosts import os_type
from phenix_apps.apps.sceptre.metadata import Simulator
from phenix_apps.apps.sceptre.stages import Stage, Steps
from phenix_apps.common import error, utils
from phenix_apps.common.logger import logger

# Files the ELK box analytics read, generated in pre-start.
ELK_FILES: Final[tuple[str, ...]] = (
    "fdlist.json",
    "reg_addrs.json",
    "sceptre_provider_restart.py",
)


class ConfigureStage(Stage):
    """Declares every injection the experiment needs, one method per component.

    The methods share no state and may run in any order.
    """

    def steps(self) -> Steps:
        return (
            ("opc", self.opcs),
            ("field devices", self.field_devices),
            ("hmi", self.hmis),
            ("scada server", self.scada_servers),
            ("engineer wkst", self.engineer_workstations),
            ("historian", self.historians),
            ("provider", self.providers),
            ("helics", self.helics),
            ("elk", self.elk),
        )

    def _windows_host(self, hostname: str, *files: tuple[str, str, str]) -> None:
        """Inject a Windows host's generated files, plus its startup scheduler.

        Each file is (name, dst, description): the source is the generated
        sceptre/<hostname>/<name>, and <name> is also the override name.
        """

        for name, dst, description in files:
            self.inject(
                hostname,
                self.sceptre_dir / hostname / name,
                dst,
                description,
                override=name,
            )
        self.app.add_sceptre_startup_injects_windows(hostname)

    def opcs(self) -> None:
        """Inject the OPC config and TopServer startup script."""

        for opc in self.hosts("opc"):
            # A HIL setup overrides opc.xml with a config listing real hardware.
            self._windows_host(
                opc.hostname,
                (
                    "opc.xml",
                    "Users/wwuser/Documents/Configs/Inject/opc.xml",
                    "OPC configuration for TopServer",
                ),
                (
                    "topserver.ps1",
                    "/sceptre/startup/30-topserver.ps1",
                    "OPC TopServer startup script",
                ),
            )

    def hmis(self) -> None:
        """Inject the HMI startup script."""

        for hmi in self.hosts("hmi"):
            self._windows_host(
                hmi.hostname,
                ("hmi.ps1", "/sceptre/startup/30-hmi.ps1", "HMI startup script"),
            )

    def scada_servers(self) -> None:
        """Inject the SCADA project (supplied or autogenerated) and its startup script."""

        for scada_server in self.hosts("scada-server"):
            host = scada_server.hostname
            scada_directory = self.sceptre_dir / host

            if "metadata" not in scada_server:
                logger.warning(f"No metadata for {host}")
                continue

            if "project" in scada_server.metadata:
                self.inject(
                    host,
                    scada_server.metadata.project,
                    "Users/wwuser/Documents/Configs/Inject/myscada.mep",
                    "SCADA project file",
                )

                # Without an automation binary, scada.mako uses alternative automation.
                if "automation" in scada_server.metadata:
                    self.inject(
                        host,
                        scada_server.metadata.automation,
                        "myscada.exe",
                        "Windows automation binary",
                    )

                startup = "scada.ps1"
            else:
                self.inject(
                    host,
                    scada_directory / "autoproject",
                    "Users/wwuser/Documents/",
                    "autogenerated SCADA project file",
                )
                startup = "scada_autoproject.ps1"

            self._windows_host(
                host, (startup, "/sceptre/startup/30-scada.ps1", "scada")
            )

    def engineer_workstations(self) -> None:
        """Inject the PuTTY config and, if configured, the auto-connect script."""

        for eng in self.hosts("engineer-workstation"):
            files = [
                (
                    "putty.ps1",
                    "/sceptre/startup/30-putty.ps1",
                    "Engineer workstation PuTTY configurations",
                )
            ]
            if "connect_interval" in eng.metadata:
                files.append(
                    (
                        "auto_winscp.ps1",
                        "/sceptre/startup/40-auto_winscp.ps1",
                        "Engineer workstation auto putty connections",
                    )
                )
            self._windows_host(eng.hostname, *files)

    def historians(self) -> None:
        """Inject the historian config and startup script."""

        for historian in self.hosts("historian"):
            self._windows_host(
                historian.hostname,
                (
                    "historian_config.txt",
                    "Users/wwuser/Documents/Configs/Inject/historian_config.txt",
                    "Historian configuration",
                ),
                (
                    "historian.ps1",
                    "/sceptre/startup/30-historian.ps1",
                    "Historian startup script",
                ),
            )

    def field_devices(self) -> None:
        """Inject startup scripts and configs for fd-servers, fd-clients and feps."""

        fds = self.hosts("fd-server")
        fdc = self.hosts("fd-client")
        fdf = self.hosts("fep")

        for fd_ in fds + fdc + fdf:
            self.inject(
                fd_.hostname,
                self.startup_dir / f"{fd_.hostname}-start.sh",
                "/etc/phenix/startup/sceptre-start.sh",
                f"{fd_.hostname} startup script",
                permissions="0744",
                override="sceptre-start.sh",
            )
            self.inject(
                fd_.hostname,
                self.sceptre_dir / fd_.hostname / "config.xml",
                "/etc/sceptre/config.xml",
                f"{fd_.hostname} config",
                override="config.xml",
            )

    def providers(self) -> None:
        """Inject simulator-specific config, case files and the startup script."""

        providers = self.hosts("provider")
        if not providers:
            msg = "No SCEPTRE providers have been configured for this experiment"
            logger.error(msg)
            raise error.AppError(msg)

        for provider in providers:
            if "metadata" not in provider:
                logger.warning(
                    f"No metadata for provider '{provider.hostname}', skipping..."
                )
                continue

            host = provider.hostname
            vm_directory = self.sceptre_dir / host
            simulator = provider.metadata.get("simulator", "")  # type: str

            if not simulator:
                logger.warning(
                    f"No simulator specified for provider '{host}', will fall back to default config"
                )

            sim = Simulator.parse(simulator)
            inject_for = simulators.INJECTIONS.get(sim, simulators.default_injections)
            inject_for(self, host, vm_directory, provider)

            if sim in simulators.YAML_CONFIGURED:
                simulators.yaml_config_injections(
                    self, host, vm_directory, provider, sim
                )

            self._provider_startup(host, provider)

    def _provider_startup(self, host: str, provider) -> None:
        win = "phenix/startup/30-sceptre-start.ps1"
        nix = "/etc/phenix/startup/sceptre-start.sh"
        dst = win if os_type(provider) == "windows" else nix
        ext = dst.split(".")[1]
        self.inject(
            host,
            self.startup_dir / f"{host}-start.{ext}",
            dst,
            "provider_startup_scripts",
            override=f"sceptre-start.{ext}",
        )

    def helics(self) -> None:
        """Inject federate configs and write the broker startup script."""

        feds = self.labelled("helics-federate")

        for fed in feds:
            win = "sceptre/helics.json"
            nix = "/etc/sceptre/helics.json"
            self.inject(
                fed.hostname,
                self.sceptre_dir / fed.hostname / "helics.json",
                nix if os_type(fed) == "linux" else win,
                "HELICS config",
                override="helics.json",
            )

        for bkr in self.labelled("helics-broker"):
            if os_type(bkr) != "linux":
                continue

            loglevel = bkr.metadata.get("helics_broker_loglevel", 3)  # 3 = summary
            logfile = bkr.metadata.get(
                "helics_broker_logfile", "/etc/sceptre/log/helics_broker.log"
            )

            startup_file = self.startup_dir / f"{bkr.hostname}-helics.sh"
            startup_file.write_text(
                f"helics_broker --autorestart --ipv4 -f {len(feds)}"
                f" --logfile={logfile}"
                f" --fileloglevel={loglevel} &\n"
            )
            utils.mark_executable(startup_file)

            self.inject(
                bkr.hostname,
                startup_file,
                "/etc/phenix/startup/helics-broker-start.sh",
                "HELICS broker start",
                override="helics.sh",
            )

    def elk(self) -> None:
        """Inject beat startup scripts and the field-device list for the ELK box."""

        for vm in self.labelled("elk"):
            if os_type(vm) != "linux":
                continue

            startup_file = self.startup_dir / f"{vm.hostname}-elk-start.sh"
            startup_file.write_text(
                "sleep 10s\nservice filebeat start\nservice metricbeat start\n"
                "service collectd start\n"
            )
            utils.mark_executable(startup_file)

            self.inject(
                vm.hostname,
                startup_file,
                "/etc/phenix/startup/elk-start.sh",
                "vm_elk_startup",
                permissions="0774",
                override="elk-start.sh",
            )

        elk = self.hosts("elk")

        if len(elk) > 1:
            msg = "There are multiple ELK boxes defined for this SCEPTRE experiment"
            logger.error(msg)
            raise error.AppError(msg)

        for filename in ELK_FILES if elk else ():
            self.inject(
                elk[0].hostname,
                self.elk_dir / filename,
                f"/etc/phenix/analytics/files/{filename}",
                "elk",
                override=filename,
            )
