version: "2"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    # - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    # - err113
    # - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    # - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoglobals
    # - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - iotamixing
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    # - mnd
    - modernize
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    # - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl_v5
    - zerologlint

  exclusions:
    warn-unused: true
    rules:
      - linters:
          - revive
        text: should have.*comment
    #   - linters:
    #       - gosec
    #     text: "G104: Errors unhandled"
    #   - linters:
    #       - errcheck
    #     text: bar\.
    #   - linters:
    #       - errcheck
    #     text: \.Close

  disable:
    - depguard
    - err113
    - errcheck
    - exhaustruct
  #   - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - mnd
  #   - noctx
    - varnamelen

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
      