name: go

env:
  GO_VERSION: 1.24.0

on:
  push:
    branches: ['**']

jobs:

  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: src/go/go.sum
      - name: Install dependencies
        working-directory: src/go
        run: make install-dev
      - name: Run lint checks
        working-directory: src/go
        run: make check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: src/go/go.sum
      - name: Run Tests
        working-directory: src/go
        run: make test
