name: python

env:
  PYTHON_VERSION: "3.12"

on:
  push:
    branches: ['**']

jobs:

  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: src/python/pyproject.toml
      - name: Install dependencies
        working-directory: src/python
        run: make install-dev
      - name: Run checks
        working-directory: src/python
        run: make check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: src/python/pyproject.toml
      - name: Run Tests
        working-directory: src/python
        run: |
          make install-dev
          make test
